name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What’s the problem or opportunity?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should change?
      placeholder: Clear, incremental proposal
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Links, screenshots, prior art

